widgy/contrib/page_builder/static/widgy/page_builder/image.admin.scss
widgy/templates/widgy/field_as_div.html

Previously the labels of every field were hidden. Now only the image
field doesn't have a label.
I was subclassing Image and setting my subclass' `css_classes` to `('page_builder', 'image')` for the icon, but I realized that my form labels were missing and I was like, WHAT?

CSS support for adding fields to Image.

---

widgy/contrib/page_builder/static/widgy/page_builder/table-theme.admin.scss
widgy/static/widgy/css/widgy_layout.scss

Eliminated the margins for InvisibleMixin

---

widgy/contrib/page_builder/static/widgy/page_builder/html.scss

This is a fix for #279 Placing quotes around left, center, etc will add the quotes in the `text-align: 'left'` which is not the same as `text-align: left`

Fixed styles in ckeditor to show justifications

---

widgy/static/daisydiff/css/diff.css

I was trying to run the r.js optimizer (with django-require) on my own code, but it threw the following error:
```
Post-processing 'daisydiff/css/diff.css' failed!
Traceback (most recent call last):
File "manage.py", line 9, in <module>
execute_from_command_line(sys.argv)
File "/var/python-environments/XXXX/lib/python2.6/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
utility.execute()
File "/var/python-environments/XXXX/lib/python2.6/site-packages/django/core/management/__init__.py", line 392, in execute
self.fetch_command(subcommand).run_from_argv(self.argv)
File "/var/python-environments/XXXX/lib/python2.6/site-packages/django/core/management/base.py", line 242, in run_from_argv
self.execute(*args, **options.__dict__)
File …
```

Fix r.js optimization errors with daisydiff

---

widgy/contrib/widgy_mezzanine/admin.py
widgy/contrib/widgy_mezzanine/views.py

This allows us to reuse the WidgyPageAdmin for other WidgyPage-like
objects.
I'm doing craaaazy things over here!

Set model at runtime for ClonePageView and UnpublishView.

---

widgy/forms.py

The whole row containing HiddenInput is hidden in django 1.7. WidgyWidget is implemented as a HiddenInput but shouldn't be hidden. Setting is_hidden=False tells the admin to show its row.

HiddenInput Django 1.7 admin compatibility

---

widgy/contrib/widgy_mezzanine/models.py
widgy/contrib/widgy_mezzanine/tests.py
widgy/contrib/widgy_mezzanine/urls.py
widgy/contrib/widgy_mezzanine/views.py

nginx has a feature where it merges slashes[0] in a URL, so for example, a URL that looks like:
```
//scripts/script.php
```
would be normalized to:
```
/scripts/script.php
```
This is great, except no it's not.  Especially because in widgy, we tend to have URLs that look like:
```
http://demo.wid.gy/widgy/preview/1///
```
but that nginx is passing through as:
```
http://demo.wid.gy/widgy/preview/1/
```
The behavior in nginx can be turned off with
```
merge_slashes off;
```
But it seems bad to require special configuration of nginx for widgy to work. Alternatively, we can urlencode the slug in the url.
[0] http://nginx.org/en/docs/http/ngx_http_core_module.html#merge_slashes
reported by @rockymeza

widgy_mezzanine preview doesn't work with default nginx config

---

widgy/contrib/widgy_mezzanine/models.py
widgy/contrib/widgy_mezzanine/tests.py
widgy/contrib/widgy_mezzanine/urls.py
widgy/contrib/widgy_mezzanine/views.py

If you're reversing the preview url by slug, your code should continue to work. This fixes the backwards compatibility problems for #233.

Preserve the old preview/form urls for backwards compatibility

---

.travis.yml

routes builds to the EC2 workers, which are faster and have caching available

use sudo: false for fun and profit

---

tests/modeltests/core_tests/models.py
tests/modeltests/core_tests/tests/forms.py
widgy/forms.py

Every once in a while, I create a widget, the content type gets stored in the database and then I go to change the `verbose_name` of that widget, but the ContentType label is never updated in the database. This patch makes sure to use the current `verbose_name` of the model class. This should also enable the internationalization of of the ContentTypeRadioInputs, although I did not write a test for that.

Better labels for ContentTypeRadioInputs.

---

docs/tutorials/widgy-mezzanine-tutorial.rst
widgy/contrib/widgy_mezzanine/admin.py

This was supposed to be removed in #197, but it somehow wasn't.
Hypothetically there are projects that use RichTextPages and WidgyPages
at the same time, it is not up to us to determine what those projects
can and cannot do.
@zmetcalf, what happened?

Don't unregister RichTextPage.

---

docs/tutorials/widgy-mezzanine-tutorial.rst

it's only been available for like a year and a half........

Recommend installing from PyPI in quickstart.

---

widgy/static/widgy/js/lib/csrf.js

Currently widgy is grabbing the csrf token out of the cookie using JavaScript. This fails if you set `CSRF_COOKIE_HTTPONLY=True`. 
We should change how we do that. I think we could just pass the csrf token in manually to the javascript.

Widgy doesn't support CSRF_COOKIE_HTTPONLY

---

CHANGELOG.rst
demo/public/css/demo.scss
setup.py
widgy/contrib/page_builder/forms/__init__.py

I was hoping that we could get the commits 757ef9d and db4129b into master without waiting for mezzanine and django-filer to be released.

We need to support django-pyscss 2.0.0

---

CHANGELOG.rst
demo/settings.py
tests/core_tests/tests/base.py
tests/core_tests/tests/test_api.py
tests/settings.py
widgy/contrib/widgy_mezzanine/tests.py
widgy/site.py
widgy/views/base.py

Hi,
When a colleague sends me a link to a preview page in widgy, I get a 403 Permission denied page.
We should redirect to the admin login form, it would improve the user experience.

Accessing a preview page unauthenticated should redirect to the admin login form

---

tests/core_tests/tests/test_core.py
widgy/exceptions.py
widgy/site.py

This is an incremental improvement.
Space for improvement would include something like suggesting where to look to fix the problem. For example, I was imagining an error message like this:
CantGoAnywhereWidget refuses to be put in Bucket. Maybe you should write a valid_child_of method for CantGoAnywhereWidget. To learn more visit the docs on compatibility (http://docs.wid.gy/en/latest/compatibility.html).
But I'm worried that the suggestion might be a misleading in some cases.

More informative messages for compatibility errors

---

demo/settings.py
docs/tutorials/widgy-mezzanine-tutorial.rst
tests/settings_contrib.py

I don't think mezzanine.boot needs to be installed -- it's only for monkey patching EXTRA_MODEL_FIELDS http://mezzanine.jupo.org/docs/packages.html#module-mezzanine.boot. It does the lazy admin registration thing, which always causes hard to debug problems. We should remove it if it's not required.

mezzanine.boot shouldn't be recommended

---

docs/tutorials/widgy-mezzanine-tutorial.rst

`south` is no longer installed as a part of `django-widgy[all]`. This
patch removes it from the tutorial.

Remove `south` from required widgy apps

---

widgy/contrib/widgy_mezzanine/migrations/0001_initial.py

The base widgy migrations had references to ReviewedVersionTracker,
which is not part of the base widgy install.  This commit changes the
dependency to VersionTracker instead, which is part of the base widgy
install.

Remove dependency for ReviewedVersionTracker in migrations

---

widgy/static/widgy/css/widgy_theme_default.scss

This CSS change hides empty widget shelves (the label "Widgets" and the double-thick underline) to clean up the layout once the shelf has been depleted.

hide empty node shelves

---

widgy/contrib/widgy_mezzanine/templates/pages/widgypage_base.html

This file is only used by the oldest widgy projects, but when using
django-compressor's offline mode, it will trigger an error because it is
missing the staticfiles templatetags library.

Add staticfiles import for widgypage_base.html

---

widgy/contrib/urlconf_include/signalhandlers.py
widgy/contrib/widgy_mezzanine/search_indexes.py
widgy/contrib/widgy_mezzanine/signals.py
widgy/signals.py

It's now called widgy_pre_index. This is necessary for django-widgy-blog, which also needs to send a pre-index signal but shouldn't depend on widgy_mezzanine.

Take widgypage_pre_index out of widgy_mezzanine and into widgy

---

tox.ini
widgy/contrib/page_builder/db/fields.py
widgy/contrib/page_builder/tests.py

In Django 1.8 to_python is not automatically called by SubfieldBase
any more. Django 1.8 provides a new method: from_db_value.
See:
https://docs.djangoproject.com/en/1.8/howto/custom-model-fields/#converting-values-to-python-objects
https://docs.djangoproject.com/en/1.8/ref/models/fields/#django.db.models.Field.from_db_value
(Note: super() may not be called in from_db_value())

Update video widget to work with Django 1.8

---

widgy/contrib/page_builder/models.py

This is required to match the model (blank = False).  This should have
been done in 8dbdd79f26, but it was incomplete.

Make HtmlForm content required.

---

widgy/contrib/page_builder/models.py

BaseLayout can be subclassed without adding to the root_choices
for WidgyPage. Layout should still function as before.

Create BaseLayout class.

---

tests/core_tests/tests/test_core.py
widgy/models/versioning.py

In Django 1.7 and 1.8 relation.model is the model the relation is
pointing from. Therefore `issubclass(rel_obj.model, VersionCommit)` was
always false, since `rel_obj.model` was either VersionTracker or
ReviewedVersionTracker.

VersionTracker with commits were filtered out from orphan()

---

widgy/contrib/form_builder/models.py
widgy/contrib/form_builder/tests.py

friendly_uuid returns bytes on python3 which is then compared
with a string type which always returns false. friendly_uuid
should return a string type on both Python 2 and Python 3.

Make friendly_uuid work correctly on Python 3

---

CHANGELOG.rst
tests/core_tests/migrations/0002_auto_20150701_1654.py
tests/core_tests/models.py
tests/core_tests/tests/test_core.py
widgy/models/base.py

- Content.clone() now copies them
- Content.get_attributes() includes them so widgets with changed
many-to-manies are considered not equal().

Handle widgets with ManyToManyFields better

---

tests/core_tests/tests/test_core.py
widgy/__init__.py

The Django behavior that necessitated deferred exceptions in Widgy
was fixed in Django 1.7, which is the oldest version Widgy now supports.
Fix #288

Remove deferred exceptions

---

widgy/contrib/form_builder/models.py

In Python 3 headers.key() is an iterator. Therefore it gets consumed
during the first yield ... for i in headers.keys()

Fix form changelist in Python 3

---

widgy/contrib/form_builder/models.py

Currently multiple choice field data in emails takes the form of
Field: [u'choice1', u'choice2']. This patch serializes the data
properly using the already defined `serialize_value` function on
form fields.

Serialize data for success emails properly

---

widgy/templates/admin/filer/base_site.html
widgy/templates/admin/filer/folder/directory_table.html

Filer now uses staticfiles rather than
filer_staticmedia_prefix.
This was removed in django-filer b29e7cc8d488f5c.

Remove deprecated filer templatetag
